{
 "title": "Sunpower",
 "time": { "from": "2024-11-10T02:24:07.285Z", "to": "2024-11-10T14:26:12.516Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{stats=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{stats=\"fault_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_from_pv\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_to_load\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Total",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"total_load_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({dc=\"pv_power\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"total_grid_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "({batt=\"out_power\", battery_num=\"1\"} < 0 )* -1",
     "legendFormat": "__auto"
    },
    {
     "expr": "({batt=\"out_power\", battery_num=\"1\"} > 0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bought",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_from_grid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_battery_charge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discharge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "{energy=\"total_battery_discharge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Self Usage %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum({ac=\"total_generated_power\"}/ on(){ac=\"total_load_power\"})*100) > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({dc=\"pv_power\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"total_grid_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{stats=\"temp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{batt=\"batt_temp\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batt V",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{batt=\"voltage\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SoC",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{batt=\"batt_soc\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batt Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{batt=\"out_power\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"total_load_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{dc=\"pv_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Power Stats",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{batt=\"out_power\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{batt=\"out_current\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{batt=\"voltage\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{batt=\"batt_soc\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Voltage-Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "{dc=\"pv_voltage\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{dc=\"pv_current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PowerInOut A",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"grid_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"load_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Gen A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Load A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"load_power\", phase=\"A\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PowerInOut B",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"grid_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"load_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Load B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"load_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "{ac=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Gen B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PowerInOut C",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"grid_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{ac=\"load_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Load C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"load_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P Gen C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ac=\"generated_power\", phase=\"C\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{stats=\"heatsink_temp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{stats=\"temp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{batt=\"batt_temp\", battery_num=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Per Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{ac=\"load_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "{energy=\"total_from_grid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{energy=\"total_from_pv\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{energy=\"total_battery_charge\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{energy=\"total_battery_discharge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EPS Load (W+A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{eps=\"power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{eps=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EPS Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "{eps=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}